services:
  web:
    image: registry.digitalocean.com/test-stuff/guitar-lessons:test
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - data
  data:
    build:
      dockerfile: ./data.dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d/

