# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.5.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: registry login
      run: doctl registry login
      
    - name: docker build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: registry.digitalocean.com/test-stuff/guitar-lessons:test
        push: true
  
    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
            docker stop thing
            docker rm thing
            docker pull registry.digitalocean.com/test-stuff/guitar-lessons:test
            docker run -d -p 4000:80 --name thing registry.digitalocean.com/test-stuff/guitar-lessons:test
      
  
